server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./h2-data-home/trace
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      save-mode: on_set_attribute
  h2:
    console:
      enabled: true

app.trace:
  geo-ip-db: classpath:geoip/GeoLite2-City.mmdb